### ISSUE TITLE
Wrong range for certain component value range

### ISSUE THREAD

**Issue by ccrownhill** [tomcl/ADDIE#3]
**Describe the bug**
In the file [`src/Renderer/UI/SelectedComponentView.fs`](https://github.com/tomcl/ADDIE/blob/master/src/Renderer/UI/SelectedComponentView.fs#L217C9-L217C50) for a value between 0.1 and 0.99 a maximum value of 0.099 is returned even though it should be 0.99:

```fs
|v when (v>=0.1 && v<1) -> 0.1,0.099,0.01
```

(line 217)

**Comment by tomcl** [comment]
if you PR it we can close this.

**Comment by ccrownhill** [comment]
I made the PR

**Comment by tomcl** [comment]
closed by #4
